spring.application.name=lightfeather

server.port=8090
# Connection Settings
#spring.datasource.url=jdbc:postgresql://localhost:5432/fyu_dbeaver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional Logging
spring.jpa.show-sql=true

# Sets the default database schema search path (default is usually 'public')
spring.jpa.properties.hibernate.default_schema=dbeaver1
spring.datasource.hikari.schema=dbeaver1


# url.for.supervisor.baseUrl=https://o3m5qixdng.execute-api.us-east-1.amazonaws.com/api/managers
supervisor.baseUrl=https://o3m5qixdng.execute-api.us-east-1.amazonaws.com
supervisor.uri=/api/managers